
name: Qmk Firmware Compiler/Builder

on:
  push:
    branches:
      - main


steps:

  - uses: actions/checkout@v1

  - name: Build Firmware
    uses: ./
    with:
      keymap-path: "keyboards/keychron/k8/keymaps/homerow"
      keyboard: "keychron/k8/v1"
      keymap: "homerow"

  - name: Upload a Firmware
    uses: actions/upload-artifact@v3.1.2
    with:
      name: firmware
      path: build
